// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCb9u3M4eZccXM6sl47g_Ps4fL6mPAjFw0',
    appId: '1:521034271601:web:eda814e67ba34e3d6744d0',
    messagingSenderId: '521034271601',
    projectId: 'neu-fall-2022-2',
    authDomain: 'neu-fall-2022-2.firebaseapp.com',
    storageBucket: 'neu-fall-2022-2.appspot.com',
    measurementId: 'G-NY0GYZD530',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCw2XIyRgsYud-VAEMBHMgPC55xqzDjJqc',
    appId: '1:521034271601:android:c9c0d081089235346744d0',
    messagingSenderId: '521034271601',
    projectId: 'neu-fall-2022-2',
    storageBucket: 'neu-fall-2022-2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDG6YATyqKR5t_RgbzkN3szndVpv2KXv9I',
    appId: '1:521034271601:ios:1c13d741a2954bde6744d0',
    messagingSenderId: '521034271601',
    projectId: 'neu-fall-2022-2',
    storageBucket: 'neu-fall-2022-2.appspot.com',
    androidClientId: '521034271601-06a0bv8gbvr5410k3ia3tc9tki6i0l60.apps.googleusercontent.com',
    iosClientId: '521034271601-5tl0m2k9o4m14qh9mm38if5m2pbsihkk.apps.googleusercontent.com',
    iosBundleId: 'com.example.complete',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDG6YATyqKR5t_RgbzkN3szndVpv2KXv9I',
    appId: '1:521034271601:ios:1c13d741a2954bde6744d0',
    messagingSenderId: '521034271601',
    projectId: 'neu-fall-2022-2',
    storageBucket: 'neu-fall-2022-2.appspot.com',
    androidClientId: '521034271601-06a0bv8gbvr5410k3ia3tc9tki6i0l60.apps.googleusercontent.com',
    iosClientId: '521034271601-5tl0m2k9o4m14qh9mm38if5m2pbsihkk.apps.googleusercontent.com',
    iosBundleId: 'com.example.complete',
  );
}
