// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwxj6_g5I0KAWEprgdLbaBBt4WvjI3xr0',
    appId: '1:40343468216:web:286f03923194fabac81c4d',
    messagingSenderId: '40343468216',
    projectId: 'neu-fall-2022',
    authDomain: 'neu-fall-2022.firebaseapp.com',
    databaseURL: 'https://neu-fall-2022-default-rtdb.firebaseio.com',
    storageBucket: 'neu-fall-2022.appspot.com',
    measurementId: 'G-SEP6LCFY7E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxYYsghqa0PLXQB-kiBRLYSbnET5NWuD4',
    appId: '1:40343468216:android:5f21a3f8481051a7c81c4d',
    messagingSenderId: '40343468216',
    projectId: 'neu-fall-2022',
    databaseURL: 'https://neu-fall-2022-default-rtdb.firebaseio.com',
    storageBucket: 'neu-fall-2022.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTMCdgzeAen_KUk0SoXOxw_Q0jOcIl86w',
    appId: '1:40343468216:ios:88b2041089901988c81c4d',
    messagingSenderId: '40343468216',
    projectId: 'neu-fall-2022',
    databaseURL: 'https://neu-fall-2022-default-rtdb.firebaseio.com',
    storageBucket: 'neu-fall-2022.appspot.com',
    androidClientId: '40343468216-2hk67qcmukkk1ei899b164rag361hqs6.apps.googleusercontent.com',
    iosClientId: '40343468216-ihbkjbup5brv7h8auq6h9tm15do6obtr.apps.googleusercontent.com',
    iosBundleId: 'com.example.complete',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTMCdgzeAen_KUk0SoXOxw_Q0jOcIl86w',
    appId: '1:40343468216:ios:88b2041089901988c81c4d',
    messagingSenderId: '40343468216',
    projectId: 'neu-fall-2022',
    databaseURL: 'https://neu-fall-2022-default-rtdb.firebaseio.com',
    storageBucket: 'neu-fall-2022.appspot.com',
    androidClientId: '40343468216-2hk67qcmukkk1ei899b164rag361hqs6.apps.googleusercontent.com',
    iosClientId: '40343468216-ihbkjbup5brv7h8auq6h9tm15do6obtr.apps.googleusercontent.com',
    iosBundleId: 'com.example.complete',
  );
}
