// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmOb-aZsQe1jWoXOOHwWe2L25FcuVABx0',
    appId: '1:317808850895:web:4520cb7fa008d88dcb44ba',
    messagingSenderId: '317808850895',
    projectId: 'flutterfire-ui-codelab-bdbff',
    authDomain: 'flutterfire-ui-codelab-bdbff.firebaseapp.com',
    storageBucket: 'flutterfire-ui-codelab-bdbff.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-KBZeMvdMtFDNhCU6YOx3j3zV2B_bBb4',
    appId: '1:317808850895:android:3ef3604ebe621004cb44ba',
    messagingSenderId: '317808850895',
    projectId: 'flutterfire-ui-codelab-bdbff',
    storageBucket: 'flutterfire-ui-codelab-bdbff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIHepeOsKT3ix6-FSkqown3ty7-GK32N0',
    appId: '1:317808850895:ios:857fc86ff1638865cb44ba',
    messagingSenderId: '317808850895',
    projectId: 'flutterfire-ui-codelab-bdbff',
    storageBucket: 'flutterfire-ui-codelab-bdbff.appspot.com',
    iosClientId: '317808850895-la3jll0mt60ds7s1rr3e243homfa052e.apps.googleusercontent.com',
    iosBundleId: 'com.example.complete',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIHepeOsKT3ix6-FSkqown3ty7-GK32N0',
    appId: '1:317808850895:ios:857fc86ff1638865cb44ba',
    messagingSenderId: '317808850895',
    projectId: 'flutterfire-ui-codelab-bdbff',
    storageBucket: 'flutterfire-ui-codelab-bdbff.appspot.com',
    iosClientId: '317808850895-la3jll0mt60ds7s1rr3e243homfa052e.apps.googleusercontent.com',
    iosBundleId: 'com.example.complete',
  );
}
